### ISSUE TITLE
Rendering JSONP with Collection View

### ISSUE THREAD

**Issue by ghost** [chaplinjs/chaplin#185]
Hi, I'm having problems to render some data from the blogger JSONP  API v3

I'm getting the following error

```
Uncaught TypeError: Object #<PostCollection> has no method 'serialize' 
```

on chaplin.js:

```
      View.prototype.getTemplateData = function() {
        var items, model, modelOrCollection, templateData, _i, _len, _ref;
        if (this.model) {
          templateData = this.model.serialize();  //*** ERROR ***
        } else if (this.collection) {
          items = [];
          _ref = this.collection.models;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            model = _ref[_i];
            items.push(model.serialize());
          }
          templateData = {
            items: items
          };
        } else {
          templateData = {};
        }
        modelOrCollection = this.model || this.collection;
        if (modelOrCollection) {
          if (typeof modelOrCollection.state === 'function' && !('resolved' in templateData)) {
            templateData.resolved = modelOrCollection.state() === 'resolved';
          }
          if (typeof modelOrCollection.isSynced === 'function' && !('synced' in templateData)) {
            templateData.synced = modelOrCollection.isSynced();
          }
        }
        return templateData;
      };
```

I'm sure I'm doing something wrong but I can't find it so far.

Thanks for your help guys.

My code is below:

CONTROLLER

```
define [
  'controllers/base/controller'
  'views/home_view',
  'views/services_view',
  'views/blog_view',
  'views/cv_view',
  'views/biography_view',
  'lib/rich_elements'
], (Controller, HomeView, ServicesView, BlogView, CvView, BiographyView, RichElements) ->
  'use strict'

  class PageController extends Controller
    historyURL: (params) ->
      ''
    blog: (params) ->
      @title ='Blog'
      @view = new BlogView()
      EnableRichElements()
      return
```

COLLECTION VIEW

```
define ["views/base/collection_view", "text!templates/post_collection_template.hbs","models/post_collection"], (CollectionView, template, PostCollection) ->
  "use strict"
  class BlogView extends CollectionView
    template: template
    container: '#maincontainer'
    autoRender: true
    model: new PostCollection()
```

TEMPLATE

```
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <td>Date</td>
            <td>Title</td>
            <td>Tags</td>
        </tr>
    </thead>
    <tbody>
        {{#each items}}
            <tr>
                <td>{{content/published}}</td>
                <td><a href="#post{{content/id}}">{{title}}</a></td>
                <td>
                    <span class="label label-warning">x</span>
                </td>
            </tr>
        {{/each}}
    </tbody>
</table>
```

MODEL (Post)

```
define [
    'chaplin',
    'models/base/model'
], (Chaplin, Model) ->
    'use strict'

    class Post extends Model
        defaults:
            kind: null
            id: null
            blog:
                id: 5158687832660982606
            published: null
            updated: null
            url: null
            selfLink: null
            title: null
            content: null
            author: 
                id: null
                displayName: null
                url: null
                image:
                    url: null
            replies:
                totalItems: null
                selfLink: null
```

COLLECTION (Post collection)

```
define [
    'chaplin',
    'models/base/collection',
    'models/post_model'
], (Chaplin, Collection, PostModel) ->
    'use strict'

    class PostCollection extends Collection
        model: new PostModel()
        url : "https://www.googleapis.com/blogger/v3/blogs/" + "" + "/posts?key=" + "" + "&callback=jsonp"
```
