### ISSUE TITLE
siteview - conditionally add/remove regions 

### ISSUE THREAD

**Issue by raviada** [chaplinjs/chaplin#632]
I have a siteview with the following regions

```
class SiteView extends View
    container: 'body'
    id: 'site-container'
    regions:
        sidebar: '#sidebar-container'
        page: '#page-container'
        header: '#header-container'
        footer: '#footer-container'
    template: template
    template = null
```

If the route is "login", I need "header, footer, page" only and any other routes, I need all the regions.

in controller.coffee i have the following code

```
beforeAction: ->
    @compose 'site', SiteView
```

if I need to conditionally compose the regions, how to do it..
for example
    if route.controller is 'login'
       .. remove sidebar

pl help

thanks
Ravi Ada
